### ISSUE TITLE
Game links not feeding through 

### ISSUE THREAD

**Issue by Peter-Hornsby** [ScorchChess/toastie-build#111]
![image](https://user-images.githubusercontent.com/68423679/143892755-b7eab887-979c-4df6-bec6-c62258bb1dfd.png)

As you can see it won't load the 'join game' and 'watch live' buttons with the start time registered

**Comment by Peter-Hornsby** [comment]
On this link: https://results.scorchapp.co.uk/t/2020worldchess/pairings/4

**Comment by theLAZYmd** [comment]
Fixed with https://github.com/aloysiuslip/whiplash/commit/816f7785d5e8e1f2f7cd3ee9774bac887889246e
