### ISSUE TITLE
* Tournaments with 10 or more rounds in a Swiss

### ISSUE THREAD

**Issue by Peter-Hornsby** [ScorchChess/toastie-build#63]
https://results.scorchapp.co.uk/t/2020Chess/pairings/1 

The Rounds with dates aren't easily readable 

Many thanks :)

**Comment by theLAZYmd** [comment]
Fixed with https://github.com/aloysiuslip/whiplash/commit/63dc0a83298e0da5c03f1d940a6b35217b98309a
See: https://results.scorchapp.co.uk/t/2020chess/pairings/1
