### ISSUE TITLE
Games showing up as aborted when they haven't been 

### ISSUE THREAD

**Issue by Peter-Hornsby** [ScorchChess/toastie-build#66]
![image](https://user-images.githubusercontent.com/68423679/96195526-e343db80-0f44-11eb-9602-e3da6824426e.png)

**Comment by Peter-Hornsby** [comment]
![image](https://user-images.githubusercontent.com/68423679/96293479-b8a86000-0fe2-11eb-98b2-d5c1033f8468.png)

Same for when they are live

**Comment by theLAZYmd** [comment]
Can you maybe put some links to the game in here next time

**Comment by theLAZYmd** [comment]
That's not currently happening in https://results.scorchapp.co.uk/t/2020stage6/pairings/6

**Comment by theLAZYmd** [comment]
or https://results.scorchapp.co.uk/t/2020stage6/pairings/7
