### ISSUE TITLE
Teams saying that they have not been paired when they have

### ISSUE THREAD

**Issue by Peter-Hornsby** [ScorchChess/toastie-build#68]
![image](https://user-images.githubusercontent.com/68423679/96773326-45d12780-13dc-11eb-80d8-777edd869af5.png)

**Comment by Peter-Hornsby** [comment]
See Abbots Bromley

**Comment by theLAZYmd** [comment]
Can't reproduce but have improved the pair remaining checker a little with https://github.com/aloysiuslip/toastie/commit/1283cf8822b1c7b16890ed5c19aa9b4cf6dfb14e

**Comment by theLAZYmd** [comment]
Think we've fixed this with 1.7.2
