### ISSUE TITLE
Scores/dates of matches not feeding/scraping through from Chess.com 

### ISSUE THREAD

**Issue by Peter-Hornsby** [ScorchChess/toastie-build#73]
![image](https://user-images.githubusercontent.com/68423679/99918921-16327980-2d12-11eb-8219-5a1f441c816b.png)

Not sure if Chess.com problem though?

**Comment by Peter-Hornsby** [comment]
* see York and Kyiv results at the bottom of the page. The game link was submitted but then nothing went through

**Comment by theLAZYmd** [comment]
Fixed with https://github.com/aloysiuslip/whiplash/commit/0ef24a88c5199eba1ce22c64298b10ea5ff2bbb0
