### ISSUE TITLE
Request for new flags: Kiribati and Solomon Islands 

### ISSUE THREAD

**Issue by Peter-Hornsby** [ScorchChess/toastie-build#87]
Hiya, as you can see teams from there have joined: 

https://results.scorchapp.co.uk/t/2020worldchess/pairings/1 

Best wishes with thanks!

**Comment by theLAZYmd** [comment]
Fixed with https://github.com/aloysiuslip/toastie/commit/23243210f9a69aab803c9274de1cd72bedfaf3f1
