### ISSUE TITLE
Request for new flag: Iran 

### ISSUE THREAD

**Issue by Peter-Hornsby** [ScorchChess/toastie-build#92]
https://www.chess.com/clubs/members/iran-vip this team has joined here: 

https://results.scorchapp.co.uk/t/2020worldchess/standings/1

Cheers

**Comment by theLAZYmd** [comment]
Finally resolved with https://github.com/aloysiuslip/whiplash/commit/097af1397f6c51cf961c23ebbd56baad766d92b0
